### ISSUE TITLE
Ability to filter based on if one uses Doppler or 1Password for secrets

### ISSUE THREAD

**Issue by samip5** [whazor/k8s-at-home-search#24]
Should be simple as looking for

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
spec:
  provider:
    doppler:
```

and OnePassword's looks like:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
spec:
  provider:
    onepassword:
```
